"""Add Transaction and Subscription models

Revision ID: 6418d8b2b310
Revises: 123456789abc
Create Date: 2026-02-24 21:40:22.520469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6418d8b2b310'
down_revision: Union[str, Sequence[str], None] = '123456789abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customization_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customization_type'), ['type'], unique=False)

    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_logs_id'))

    op.drop_table('maintenance_logs')
    with op.batch_alter_table('servicerequest', schema=None) as batch_op:
        batch_op.alter_column('mechanic_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    with op.batch_alter_table('servicerequest', schema=None) as batch_op:
        batch_op.alter_column('mechanic_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('maintenance_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('action_taken', sa.VARCHAR(), nullable=False),
    sa.Column('score_impact', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('customization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customization_type'))
        batch_op.drop_index(batch_op.f('ix_customization_id'))

    op.drop_table('customization')
    # ### end Alembic commands ###
