"""Add ServiceFeedback model

Revision ID: ed88fe0b364e
Revises: 5128313f0e37
Create Date: 2026-02-25 11:48:57.865103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed88fe0b364e'
down_revision: Union[str, Sequence[str], None] = '5128313f0e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servicefeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_ai_accurate', sa.Boolean(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('technical_match_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['service_request_id'], ['servicerequest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_request_id')
    )
    with op.batch_alter_table('servicefeedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicefeedback_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicefeedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicefeedback_id'))

    op.drop_table('servicefeedback')
    # ### end Alembic commands ###
